### ISSUE TITLE
[AVM Module Issue]: Unable to import cluster deployed via portal.

### ISSUE THREAD

**Issue by brmcsorley** [Azure/terraform-azurerm-avm-res-azurestackhci-cluster#28]
### Check for previous/existing GitHub issues

- [x] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### Description

If you have a cluster created via Azure Portal, and the azapi_resource.validatedeploymentsetting resource doesn't match what is expected via this AVM module, you cannot import the cluster into TF State.

![Image](https://github.com/user-attachments/assets/5797937e-ec06-4970-ae5f-c2ed65bba1a6)

The azapi_resource.validatedeploymentsetting to my knowledge cannot be updated once the cluster is deployed.  

Would it be possible to add a variable to designate that the cluster was deployed via the Portal, and if true have the lifecycle changes in validate.tf ignore body.properties as a whole?

**Comment by duzitong** [comment]
Hi @brmcsorley , new parameters are added to define compute network jumbo packet and technology for RDMA. Please check whether it's fixed.
